# Project Euler: Challenge 002 - http://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
#
# Answer: 4613732

def fibonacci(n)
  ((n == 1) || (n == 2)) ? 1 : fibonacci(n - 1) + fibonacci(n - 2);
end

def even?(n)
  (n % 2) == 0
end

i, r, t, = 2, 0, 0;
while (r <= 4000000) do
  i += 1
  t = fibonacci(i)
  r += even?(t) ? t : 0
end

p r
