// Project Euler: Challenge 002 - http://projecteuler.net/problem=2
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.
//
// Answer: 4613732

package main

import "fmt"

func main() {
  var a int = 0
  var b int = 1

  var result int = 0
  var temp int = 0

  for a <= 4000000 {
    if a % 2 == 0 {
      result += a
    }

    temp = a
    a = b
    b = temp + b
  }

  fmt.Println(result)
}
